### ISSUE TITLE
How does tracing work for nginx sidecar? 

### ISSUE THREAD

**Issue by Shuanglu** [nginxinc/nginx-service-mesh#66]
Hi team, I'm testing the nginx service mesh. I have configured the tracing backend as the 'open-telemetry agent' and from sidecar configuration i could find below. The traces are expected to be sent from app to otel-agent and then otel-collector and to datadog eventually. 

```
exporter = "otlp"
processor = "batch"

[exporters.otlp]
host = "otel-agent.sandbox-infra"
port = 9411

[processors.batch]
max_queue_size = 2048
schedule_delay_millis = 5000
max_export_batch_size = 512

[service]
name = "productpage-v1-nginx"

[sampler]
name = "TraceIdRatioBased"
ratio = 1
parent_based = true
```
```
grep -Ri '/etc/nginx/otel-nginx.toml' /etc/nginx/*
/etc/nginx/nginx.conf:    opentelemetry_config /etc/nginx/otel-nginx.toml
```
However, i didn't find any trace of the nginx level in my datadog after I ran the test. I tried to capture the networking trace between application pod and otel-agent on the nodes where the applications are running on and found below.  I also configured my nginx ingress controller to export traces to the otel-agent and it's written in the nginx-config configmap and works fine. 
is there anything I missed or anything could help me to troubleshoot the issue?
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/6046716/170003176-2bb9b63f-b148-4ff2-9cc9-18cc9badf81d.png">

**Comment by sjberman** [comment]
Can you share the configuration options you used when deploying the mesh?

**Comment by sjberman** [comment]
Do you see any errors relating to opentelemetry in the logs of the sidecar?

**Comment by Shuanglu** [comment]
> Can you share the configuration options you used when deploying the mesh?

Below is my configuration of the mesh 
```
shuanglu@ShuangLu sandbox-shuang-v2_opentelemetry % helm get values nginx-service-mesh -n nginx-system
USER-SUPPLIED VALUES:
autoInjection:
  disable: true
  disabledNamespaces: []
  enabledNamespaces:
  - nginx-demo1
deployGrafana: false
mtls:
  caKeyType: ec-p256
  caTTL: 720h
  mode: permissive
  persistentStorage: "off"
  spireServerKeyManager: disk
  svidTTL: 1h
  trustDomain: cluster.local
  upstreamAuthority: {}
nginxErrorLogLevel: debug
prometheusAddress: ""
telemetry:
  exporters:
    otlp:
      host: otel-agent.sandbox-infra
      port: 9411
  samplerRatio: 1
tracing: null
```

I opened debug log and I could find the error below in the sidecar
```
Error] File: /opentelemetry-cpp/exporters/otlp/src/otlp_grpc_exporter.cc:132[OTLP TRACE GRPC Exporter] Export() failed: failed to connect to all addresses
```
networking trace shows it got 400 return
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/6046716/170648130-833126dc-8d91-485f-8a8b-1db7aa88eaff.png">

**Comment by sjberman** [comment]
I believe by default the otel agent listens on port 4317 for otlp traces. I'm assuming you have a Zipkin backend? (port 9411 is what zipkin listens on). Since traces are forwarded from the sidecar to the otel-agent, and not directly to Zipkin, your port in the telemetry config should probably be 4317, and then the otel agent itself is configured to send to Zipkin.

**Comment by Shuanglu** [comment]
> I believe by default the otel agent listens on port 4317 for otlp traces. I'm assuming you have a Zipkin backend? (port 9411 is what zipkin listens on). Since traces are forwarded from the sidecar to the otel-agent, and not directly to Zipkin, your port in the telemetry config should probably be 4317, and then the otel agent itself is configured to send to Zipkin.

in the otel-agent conf, we use 'zipkin' as a receiver. 
```
  otel-agent-config: |
    receivers:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          load:
      otlp:
        protocols:
          grpc:
          http:
      jaeger:
        protocols:
          grpc:
          thrift_compact:
          thrift_http:
      zipkin:
    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          # resourcedetection must come before k8s_tagger
          processors: [batch, resourcedetection, k8s_tagger]
          exporters: [otlp]
        traces:
          receivers: [otlp, jaeger, zipkin]
          # resourcedetection must come before k8s_tagger
          processors: [memory_limiter, resourcedetection, k8s_tagger, batch, attributes/nginx, attributes/envoy, resource/datadog]
          # exporters: [otlp, file]
          exporters: [otlp]
```
if I check the port status in the net ns, it returns below
```
ubuntu@ip-172-21-11-208:~$ sudo nsenter -t 115867 -n netstat -tulnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0      0 :::8888                 :::*                    LISTEN      115867/otelcontribc 
tcp6       0      0 :::14268                :::*                    LISTEN      115867/otelcontribc 
tcp6       0      0 :::4317                 :::*                    LISTEN      115867/otelcontribc 
tcp6       0      0 :::55680                :::*                    LISTEN      115867/otelcontribc 
tcp6       0      0 :::55681                :::*                    LISTEN      115867/otelcontribc 
tcp6       0      0 :::9411                 :::*                    LISTEN      115867/otelcontribc 
tcp6       0      0 :::14250                :::*                    LISTEN      115867/otelcontribc 
tcp6       0      0 :::13133                :::*                    LISTEN      115867/otelcontribc 
udp6       0      0 :::6831                 :::*                                115867/otelcontribc 
```
I also have kuma installed and use the otel-agent as tracing receiver and it works fine
```
piVersion: v1
items:
- apiVersion: kuma.io/v1alpha1
  kind: Mesh
  metadata:
    annotations:
      k8s.kuma.io/mesh-defaults-generated: "true"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kuma.io/v1alpha1","kind":"Mesh","metadata":{"annotations":{},"name":"default"},"spec":{"logging":{"backends":[{"conf":{"path":"/dev/stdout"},"name":"file","type":"file"}],"defaultBackend":"file"},"metrics":{"backends":[{"conf":{"path":"/metrics","port":5670,"skipMTLS":false,"tags":{"kuma.io/service":"dataplane-metrics"}},"name":"prometheus-1","type":"prometheus"}],"enabledBackend":"prometheus-1"},"tracing":{"backends":[{"conf":{"url":"http://otel-agent.sandbox-infra:9411/api/v2/spans"},"name":"otel-agent","sampling":100,"type":"zipkin"}],"defaultBackend":"otel-agent"}}}
    creationTimestamp: "2022-05-26T10:17:39Z"
    generation: 2
    name: default
    resourceVersion: "75069"
    uid: 5ae82de3-4515-4973-bfbf-9e0801aff200
  spec:
    logging:
      backends:
      - conf:
          path: /dev/stdout
        name: file
        type: file
      defaultBackend: file
    metrics:
      backends:
      - conf:
          path: /metrics
          port: 5670
          skipMTLS: false
          tags:
            kuma.io/service: dataplane-metrics
        name: prometheus-1
        type: prometheus
      enabledBackend: prometheus-1
    tracing:
      backends:
      - conf:
          url: http://otel-agent.sandbox-infra:9411/api/v2/spans
        name: otel-agent
        sampling: 100
        type: zipkin
      defaultBackend: otel-agent
```

**Comment by Shuanglu** [comment]
> Can you try configuring the mesh telemetry settings with port 4317 instead of 9411? I'm curious what the outcome would be.

a little interesting... it works now but why? 
I captures the traces and between nginx sidecar and otel-agent, it returns below
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/6046716/171217944-8d6ab36a-0985-486c-8a87-ed5d75a5a919.png">
between kuma and otel-agent, kuma sent POST request with span detail instead.
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/6046716/171218625-49c33046-b755-4a61-9592-d8ec97bbb4d1.png">

**Comment by sjberman** [comment]
Port 4317 is the OTLP gRPC exporter port for the otel collector, which is what the otel nginx library supports for trace forwarding.

Kuma has their own implementation that is unrelated to ours.

**Comment by Shuanglu** [comment]
> Can you try configuring the mesh telemetry settings with port 4317 instead of 9411? I'm curious what the outcome would be.

interesting, it started 

> Port 4317 is the OTLP gRPC exporter port for the otel collector, which is what the otel nginx library supports for trace forwarding.
> 
> Kuma has their own implementation that is unrelated to ours.

so if my otel is using zipkin as a receiver, I should configure nginx to use opentracing instead of otel, correct?

**Comment by sjberman** [comment]
You can still forward your traces to your zipkin backend using otel, your otel config would use otlp as receiver, and zipkin as the exporter. Something like this would probably work:

```
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      zipkin:
        endpoint: "path-to-zipkin:9411"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [zipkin]
```

Opentracing, while still supported at the moment, is an archived project that is pushing towards using otel instead.
